### PR TITLE
Add support for scala 2.12 cross compilation

### PR DESCRIPTION
**Pull request by avillalain**
The following changes provide support cross compilation for scala 2.12 and scala 2.11. 

It also adds support for play 2.6 in case the scala version is 2.12

A couple changes worth noting: 
- Change ShouldMatchers in favor of MustMatchers. Latest version of scalatest deprecated ShouldMatchers. In order to reuse tests and do not have multiple tests per scala version, we change it to MustMatchers

- New classes are introduced to allow tests to be reused independent of scala version.

### CODE REVIEW

**Comment by treppo** [comment]
Please take into consideration, that we had to switch to must matchers in scala test as should matchers are deprecated (as angel pointed out) and deprecation warnings are being escalated to errors in the build, as this is how the scala compiler is configured in `build.sbt`

**Comment by andreas-schroeder** [comment]
:+1: verified that the resulting 2.11 library is non-breaking and works as a drop-in replacement for the existing one. 

Merging this PR will therefore only need a patch-level version upgrade on release (currently, it would be 1.1.2).

**Comment by treppo** [comment]
to use different scala versions for building, see https://docs.travis-ci.com/user/languages/scala/

**Comment by treppo** [comment]
awesome, thanks!

**Pull request merged**
