### PR TITLE
Add generalized toggleStringForFilter method

### PR DESCRIPTION
**Pull request by kraus-as24**
A new generalized method toggleStringForFilter to generate a toggle string from toggles that satisfy the filter condition.

This is work in progress and serves for discussion of a solution with Lucas McLaren!! Missing:

- Unit tests
- Testing with client projects

### CODE REVIEW

**Comment by pgarbe** [comment]
What's the use case behind?

**Comment by kraus-as24** [comment]
The use case is that we (gecloud) need finer grained toggle strings than currently available by getToggleStringForService to pass them to fragments. A filter as suggested would allow us to control which toggles take part in the toggle string. We can evaluate for example multiple tags. One reason to do this is to not invalidate caching if we pass more toggles than needed to a fragment.

**Comment by andreas-schroeder** [comment]
Merging this PR would enable to write 

``` scala
toggling.toggleStringForFilter { case (tags, condition) => ??? }
```

One question that springs up to me is why you would want to filter on conditions as well, and not only on tags. 
Also, my suggestion would be to go for a different solution to write allowing

``` scala
toggling().filter { case (tags, condition) => ??? }.buildString
```

where `togging.apply()` returns a traversable, and `buildString` is based on an implicit conversion of the traversable type that is returned by `toggling.apply()`. 

This would 
* enable filtering and other transformations on toggles, and also
* clearly separating the concerns of filtering and building the toggle string.

If we go that route, I would mark the method `forService` as deprecated.

**Comment by gthuller** [comment]
@andreas-schroeder We have a toguru javascript client (which is very similar to our "old" feature bee js client).

The feature bee and toguru javascript client read a custom html tag and enable us to toggle javascript code. The output looks like this:

```
<feature-bee active-toggles="listingDetailApi,opsAds,useClassifiedDataV2Table,seoIndex,showHighlightsInSubtitle,lastInspectionInfo"></feature-bee>
````

The toguru client was implemented slightly different and it outputs all toggles for our service:

```
<toguru service="classified-detail" toggle-string="gecloud-fair-price=false|gecloud-price-authority-it=false|gecloud-price-authority-nl=false|gecloud-price-lightbox-information-fragment=true"></toguru>
```

In my opinion it's a *very bad thing*. If we output the OFF Toggles, everyone (competitors inclusive) that looks into our source code is able to see all the toggles we have and manually set them to ON in order to see what are developing. Therefore I would like to filter for Conditions as well (of course we could parse the string and with an simple regex remove unneeded values, but in this case we would couple this regex to your buildstring logic. That would be hacky)

The ```forService``` method would be therefore also obsolete. As far as I know it's only used by Revolistion to include us, so that'd be easy to replace

**Comment by lucmclaren** [comment]
Due to an alternative solution https://github.com/AutoScout24/toguru-scala-client/pull/19 I will close this PR.

**Pull request closed without merging**
